//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 02:48:12 odp. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.apigee.com/wadl/2010/07/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.abra.dto.api.wadl._2010._07;
